0 = "success"
-1 = "fail"
20001 = "Token missing"
20002 = "Token expired"
20003 = "Token error"
30001 = "User not found"
30002 = "Password error"
30003 = "UserName or Password error"
30004 = "Account locked, contact us"
30005 = "Invalid User ID"
30006 = "Username is already registered"
30007 = "Old password incorrect"
30008 = "Balance Not enough"
40001 = "Invalid Parameters"
40002 = "Object not found"
40003 = "Object already existed"
40004 = "Parameters missing or incorrect type"
50001 = "Internal server error"
60001 = "Quest finished"
60002 = "Quest type error"
70001 = "channel crowded, try later"
70002 = "balance not enough, please charge"
70101 = "Activity not found"
70102 = "Can only participate once"
70103 = "The current session is full"
70104 = "already got, Please check the record"
70105 = "Please unlock the task first before participating"