0 = "berhasil"
-1 = "gagal"
20001 = "Token hilang"
20002 = "Token kedaluwarsa"
20003 = "Kesalahan Token"
30001 = "Pengguna tidak ditemukan"
30002 = "Kesalahan kata sandi"
30003 = "Nama pengguna atau kata sandi salah"
30004 = "Akun terkunci, hubungi kami"
30005 = "ID pengguna tidak valid"
30006 = "Nama pengguna sudah terdaftar"
30007 = "Kata sandi lama salah"
30008 = "Saldo tidak cukup"
40001 = "Parameter tidak valid"
40002 = "Objek tidak ditemukan"
40003 = "Objek sudah ada"
40004 = "Parameter hilang atau jenis salah"
50001 = "Kesalahan server internal"
60001 = "Misi selesai"
60002 = "Kesalahan jenis misi"
70001 = "Saluran sibuk, coba lagi nanti"
70002 = "Saldo tidak cukup, silakan isi ulang"
70101 = "Aktivitas tidak ditemukan"
70102 = "Hanya dapat berpartisipasi sekali"
70103 = "Sesi saat ini penuh"
70104 = "Sudah didapat, silakan periksa catatan"
