0 = "成功"
-1 = "失敗"
20001 = "トークンがありません"
20002 = "トークンの期限が切れました"
20003 = "トークンエラー"
30001 = "ユーザーが見つかりません"
30002 = "パスワードエラー"
30003 = "ユーザー名またはパスワードが間違っています"
30004 = "アカウントがロックされています。お問い合わせください"
30005 = "無効なユーザーID"
30006 = "ユーザー名は既に登録されています"
30007 = "古いパスワードが正しくありません"
30008 = "残高が不足しています"
40001 = "無効なパラメーター"
40002 = "オブジェクトが見つかりません"
40003 = "オブジェクトは既に存在しています"
40004 = "パラメーターが欠落しているか、タイプが正しくありません"
50001 = "内部サーバーエラー"
60001 = "クエストが完了しました"
60002 = "クエストタイプエラー"
70001 = "チャンネルが混雑しています。後でもう一度試してください"
70002 = "残高が不足しています。チャージしてください"
70101 = "アクティビティが見つかりません"
70102 = "一度だけ参加できます"
70103 = "現在のセッションは満員です"
70104 = "既に受け取りました。記録を確認してください"
70105 = "タスクをアンロックしてから参加してください"
70106 = "イベントは終了しました"
70107 = "すでに抽選に参加しています"
70108 = "単一の金額は0.01未満にすることはできません"
