0 = "성공"
-1 = "실패"
20001 = "토큰이 없습니다"
20002 = "토큰이 만료되었습니다"
20003 = "토큰 오류"
30001 = "사용자를 찾을 수 없습니다"
30002 = "비밀번호 오류"
30003 = "사용자 이름 또는 비밀번호가 잘못되었습니다"
30004 = "계정이 잠겼습니다. 문의하세요"
30005 = "잘못된 사용자 ID"
30006 = "사용자 이름이 이미 등록되어 있습니다"
30007 = "기존 비밀번호가 잘못되었습니다"
40001 = "잘못된 매개변수"
40002 = "대상을 찾을 수 없습니다"
40003 = "대상이 이미 존재합니다"
40004 = "매개변수가 누락되었거나 유형이 잘못되었습니다"
50001 = "내부 서버 오류"
60001 = "퀘스트가 완료되었습니다"
60002 = "퀘스트 유형 오류"
70001 = "채널이 혼잡합니다. 나중에 다시 시도하세요"
70002 = "잔액이 부족합니다. 충전해 주세요"
70101 = "활동을 찾을 수 없습니다"
70102 = "한 번만 참여할 수 있습니다"
70103 = "현재 세션이 가득 찼습니다"
70104 = "이미 받았습니다. 기록을 확인하세요"
