0 = "sucesso"
-1 = "falha"
20001 = "Token ausente"
20002 = "Token expirado"
20003 = "Erro no Token"
30001 = "Usuário não encontrado"
30002 = "Erro de senha"
30003 = "Nome de usuário ou senha incorretos"
30004 = "Conta bloqueada, entre em contato"
30005 = "ID de usuário inválido"
30006 = "Nome de usuário já está registrado"
30007 = "Senha antiga incorreta"
40001 = "Parâmetros inválidos"
40002 = "Objeto não encontrado"
40003 = "Objeto já existe"
40004 = "Parâmetros ausentes ou tipo incorreto"
50001 = "Erro interno do servidor"
60001 = "Missão concluída"
60002 = "Erro de tipo de missão"
70001 = "Canal cheio, tente mais tarde"
70002 = "Saldo insuficiente, por favor recarregue"
70101 = "Atividade não encontrada"
70102 = "Somente uma participação é permitida"
70103 = "A sessão atual está cheia"
70104 = "Já recebido, verifique o histórico"
