0 = "สำเร็จ"
-1 = "ล้มเหลว"
20001 = "ไม่มีโทเค็น"
20002 = "โทเค็นหมดอายุ"
20003 = "โทเค็นผิดพลาด"
30001 = "ไม่พบผู้ใช้"
30002 = "รหัสผ่านผิดพลาด"
30003 = "ชื่อผู้ใช้หรือรหัสผ่านไม่ถูกต้อง"
30004 = "บัญชีถูกล็อก โปรดติดต่อเรา"
30005 = "รหัสผู้ใช้ไม่ถูกต้อง"
30006 = "ชื่อผู้ใช้ได้รับการลงทะเบียนแล้ว"
30007 = "รหัสผ่านเก่าไม่ถูกต้อง"
30008 = "ยอดคงเหลือไม่เพียงพอ"
40001 = "พารามิเตอร์ไม่ถูกต้อง"
40002 = "ไม่พบวัตถุ"
40003 = "วัตถุมีอยู่แล้ว"
40004 = "พารามิเตอร์ขาดหายหรือประเภทไม่ถูกต้อง"
50001 = "ข้อผิดพลาดของเซิร์ฟเวอร์ภายใน"
60001 = "ภารกิจเสร็จสมบูรณ์"
60002 = "ข้อผิดพลาดของประเภทภารกิจ"
70001 = "ช่องสัญญาณแออัด ลองใหม่อีกครั้ง"
70002 = "ยอดคงเหลือไม่เพียงพอ กรุณาเติมเงิน"
70101 = "ไม่พบกิจกรรม"
70102 = "สามารถเข้าร่วมได้ครั้งเดียว"
70103 = "เซสชันปัจจุบันเต็ม"
70104 = "ได้รับแล้ว โปรดตรวจสอบบันทึก"
70105 = "กรุณาปลดล็อกภารกิจก่อนเข้าร่วม"
70106 = "กิจกรรมสิ้นสุดแล้ว"
70107 = "คุณได้เข้าร่วมการจับรางวัลแล้ว"
