0 = "thành công"
-1 = "thất bại"
20001 = "Thiếu Token"
20002 = "Token đã hết hạn"
20003 = "Lỗi Token"
30001 = "Không tìm thấy người dùng"
30002 = "Lỗi mật khẩu"
30003 = "Tên người dùng hoặc mật khẩu không đúng"
30004 = "Tài khoản đã bị khóa, liên hệ chúng tôi"
30005 = "ID người dùng không hợp lệ"
30006 = "Tên người dùng đã được đăng ký"
30007 = "Mật khẩu cũ không đúng"
40001 = "Tham số không hợp lệ"
40002 = "Không tìm thấy đối tượng"
40003 = "Đối tượng đã tồn tại"
40004 = "Thiếu tham số hoặc loại không đúng"
50001 = "Lỗi máy chủ nội bộ"
60001 = "Nhiệm vụ đã hoàn thành"
60002 = "Lỗi loại nhiệm vụ"
70001 = "Kênh quá tải, thử lại sau"
70002 = "Số dư không đủ, vui lòng nạp tiền"
70101 = "Không tìm thấy hoạt động"
70102 = "Chỉ có thể tham gia một lần"
70103 = "Phiên hiện tại đã đầy"
70104 = "Đã nhận, vui lòng kiểm tra hồ sơ"
